name: Sync to Hugging Face hub

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-lastest
    
    steps:
      - uses: action/checkout@v2
        with:
          fetch-depth: 0
      - name: Add remote
        env:
          HF: ${{ secrets.HF }}
        run: git remote add space https://sonmike:$HF@huggingface.co/spaces/sonmike/demo2
      - name: Push to hub
        env:
          HF: ${{ secrets.HF }}
        run: git push --force https://sonmike:$HF@huggingface.co/spaces/sonmike/demo2 main

